In [74]:
import pandas as pd
import streamlit as st

# 엑셀 파일 불러오기 (sheet_name으로 특정 시트 지정 가능)
df_raw = pd.read_excel("etf_raw_daily.xlsx", sheet_name='FF_d')

In [3]:
ff_d = pd.DataFrame(df_raw.iloc[13:,])
ff_d = ff_d.rename( columns = df_raw.iloc[10,1:])
ff_d = ff_d.set_index('Unnamed: 0')
ff_d

,SPY US Equity,VOO US Equity,IVV US Equity,VTI US Equity,QQQ US Equity,VUG US Equity,1306 JP Equity,VEA US Equity,VTV US Equity,IEFA US Equity,...,ENCO LN Equity,CCUSAS SW Equity,AAAU US Equity,BAR US Equity,USO US Equity,DBA US Equity,ROLL LN Equity,CGL CN Equity,ZGOLD TI Equity,XGDE GR Equity
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
2019-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-30,224.7472,55.2044,-48.3705,-96.9306,-190.9156,15.8744,-0.0147,0.534,20.4527,0,...,NaN,0,0,0,40.0303,0,0,0,NaN,NaN
2019-12-31,4572.9244,20.2073,-97.032,163.3729,148.8862,15.5704,NaN,0.2451,37.0816,0,...,NaN,0,0,0,-52.4127,0,0,0,NaN,NaN
2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-27,6141.6511,-56.5979,-240.8267,66.3541,4342.9273,-9.5818,-0.1605,0.472,-8.6908,0,...,0,0,0,0,179.5089,0,18.4209,0,0,0
2025-01-28,-3295.6286,870.5774,-2430.4577,-27.5649,-2427.8609,48.8735,37.3446,0.5818,51.7528,0,...,-0.419,0,0,0,7.8694,0,0.7641,0,0,0
2025-01-29,-30.0939,455.8879,-1028.1164,148.9077,-1458.4165,158.1184,0,1.5758,58.6136,0,...,0,0,9.5358,0,-30.9899,0,1.535,3.7706,0,1.1816
2025-01-30,-2813.5169,-653.4532,1884.7172,144.2026,444.7298,32.476,0,0.1419,98.1612,0,...,-1.8148,0,0,0,15.5198,0,0,0,0,0
2025-01-31,-3341.3456,891.1122,120.9886,178.9666,-1619.8287,41.8794,0.0683,0.733,208.1766,0,...,NaN,NaN,0,0,-30.9572,2.7586,0,0,0,NaN

In [4]:
ff_d_to_w = ff_d.resample('W-FRI').sum()

In [5]:
universe_df = pd.read_csv('universe.csv')
universe_df = universe_df.set_index('Full_ticker')

In [6]:
etf_ff = pd.concat([universe_df,ff_d_to_w.T.iloc[:,-56:]], axis=1,join ="inner")
etf_ff

,NAME,Ticker,Asset,Strategy1,Strategy2,Strategy3,DM/EM,Country,2024-01-12 00:00:00,2024-01-19 00:00:00,...,2024-11-29 00:00:00,2024-12-06 00:00:00,2024-12-13 00:00:00,2024-12-20 00:00:00,2024-12-27 00:00:00,2025-01-03 00:00:00,2025-01-10 00:00:00,2025-01-17 00:00:00,2025-01-24 00:00:00,2025-01-31 00:00:00
SPY US Equity,SPDR S&P 500 ETF Trust,SPY US,주식,Blend,Large,NaN,DM,US,-6753.4355,-8866.9204,...,964.0193,3929.8612,15134.5138,-7005.6693,-6886.1554,4892.1516,-3405.1734,3304.9024,-13614.2772,-3338.9339
VOO US Equity,Vanguard S&P 500 ETF,VOO US,주식,Blend,Large,NaN,DM,US,3106.5062,2121.7666,...,1358.62,-4396.1045,1873.7186,4207.2357,6043.9611,5242.9439,6615.4745,5242.1602,6251.2023,1507.5264
IVV US Equity,iShares Core S&P 500 ETF,IVV US,주식,Blend,Large,NaN,DM,US,1276.7122,3090.2757,...,4250.3174,-416.6569,-9619.997,35889.1081,-5567.4839,2102.6933,321.7613,2339.7929,-1641.832,-1693.695
VTI US Equity,Vanguard Total Stock Market ETF,VTI US,주식,Blend,NaN,NaN,DM,US,731.0607,340.6451,...,761.2384,3235.1818,1630.575,-1056.0663,384.2798,217.0739,1242.362,1234.466,853.2683,510.8661
QQQ US Equity,Invesco QQQ Trust Series 1,QQQ US,주식,Growth,Large,NaN,DM,US,816.5877,1206.3163,...,2842.4523,-1627.9412,-1269.4754,1924.9817,-1542.1743,2840.1391,-1148.4438,1141.9194,1991.9018,-718.449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DBA US Equity,Invesco DB Agriculture Fund,DBA US,원자재,agriculture,NaN,NaN,NaN,NaN,-23.7017,-13.5115,...,0,-10.6335,5.4944,4.125,7.8237,3.9485,17.0231,10.6576,8.1921,2.7586
ROLL LN Equity,iShares Bloomberg Enhanced Roll Yield Commodit...,ROLL LN,원자재,diversified,NaN,NaN,NaN,NaN,11.9866,9.0798,...,-17.635,3.2934,15.3148,-557.5148,-5.4512,-1.3318,0,-2.2984,-2.9332,20.72
CGL CN Equity,iShares Gold Bullion ETF,CGL CN,원자재,Precious_metals,NaN,NaN,NaN,NaN,0,0,...,0,-7.4377,-7.4847,0,0,0,3.6206,0,0,3.7706
ZGOLD TI Equity,Ziraat Portfoy Gold Participation ETF,ZGOLD TI,원자재,Precious_metals,NaN,NaN,NaN,NaN,0,33.1136,...,0,0,0,0,-69.7824,-288.3062,-74.235,-14.4497,0,0
XGDE GR Equity,Xtrackers IE Physical Gold EUR Hedged ETC Secu...,XGDE GR,원자재,Precious_metals,NaN,NaN,NaN,NaN,2.653,-1.0578,...,1.152,1.1669,-5.0184,33.681,-8.3151,-1.1356,0,31.4298,-1.4521,1.1816

In [7]:
stock_ff_12w = etf_ff[etf_ff['Asset']=="주식"].iloc[:,8:].sum()
bond_ff_12w = etf_ff[etf_ff['Asset']=="채권"].iloc[:,8:].sum()
commodity_ff_12w = etf_ff[etf_ff['Asset']=="원자재"].iloc[:,8:].sum()

In [8]:
asset_ff_12w = pd.concat([stock_ff_12w,bond_ff_12w,commodity_ff_12w],axis=1)

In [9]:
asset_ff_12w.columns = ['Stock','Bond','Commodity']

In [10]:
asset_ff_12w = asset_ff_12w.astype(int)
asset_ff_12w

                     Stock   Bond  Commodity
2024-01-12 00:00:00   1774  13272       -930
2024-01-19 00:00:00   9017   3329       -448
2024-01-26 00:00:00  27987   4429        -25
2024-02-02 00:00:00  10503   4402       -458
2024-02-09 00:00:00  30068   3010       -890
2024-02-16 00:00:00  14230   1323       -758
2024-02-23 00:00:00  13083   4839      -1131
2024-03-01 00:00:00  23602   2488       -317
2024-03-08 00:00:00  21780   7877       -966
2024-03-15 00:00:00  53318   1558       1095
2024-03-22 00:00:00  -3874   4437        735
2024-03-29 00:00:00  25164   2864        599
2024-04-05 00:00:00  16371   8391        396
2024-04-12 00:00:00  -6977   3803       -699
2024-04-19 00:00:00   9995    798       -229
2024-04-26 00:00:00   8495   5568      -1445
2024-05-03 00:00:00   8900   8109       -246
2024-05-10 00:00:00  18344   9606       -566
2024-05-17 00:00:00  17108   6918       1205
2024-05-24 00:00:00   6486   1425       -800
2024-05-31 00:00:00  13580   6331        681
2024-06-07 00:00:00   9501   8888        593
2024-06-14 00:00:00  10556   5310       -546
2024-06-21 00:00:00  40812   6792        265
2024-06-28 00:00:00  20208   5664        473
2024-07-05 00:00:00   3791   7963        710
2024-07-12 00:00:00  38473  12161        414
2024-07-19 00:00:00  44409   9759       1030
2024-07-26 00:00:00  13933  10143       1336
2024-08-02 00:00:00  19890   6358       -212
2024-08-09 00:00:00   7206   3800      -1189
2024-08-16 00:00:00  17584   9684        196
2024-08-23 00:00:00  21060   9842        392
2024-08-30 00:00:00  12441   8042        690
2024-09-06 00:00:00   7573  10134         53
2024-09-13 00:00:00   2254  10183       1009
2024-09-20 00:00:00  25972   4822       -295
2024-09-27 00:00:00  39593   6030        826
2024-10-04 00:00:00  24214   7295        499
2024-10-11 00:00:00  32509   6305       -360
2024-10-18 00:00:00  22118   8585       2456
2024-10-25 00:00:00  10804   2500       1383
2024-11-01 00:00:00  14247  10764        191
2024-11-08 00:00:00  56113   8956       -604
2024-11-15 00:00:00  34704    -17      -1764
2024-11-22 00:00:00  14101   9326        605
2024-11-29 00:00:00  24811   3659       -292
2024-12-06 00:00:00  16106   7403       -904
2024-12-13 00:00:00  31127   9114       -706
2024-12-20 00:00:00  64990   -723        736
2024-12-27 00:00:00  -8030   5090       -249
2025-01-03 00:00:00  31209   6531       -356
2025-01-10 00:00:00  13686   9217        507
2025-01-17 00:00:00  27398   7371       1764
2025-01-24 00:00:00   5965   6440      -1503
2025-01-31 00:00:00   8456   7255       1083

In [11]:
asset_ff_12w.to_csv('asset_ff_12w.csv')

# AUM_timeseries

In [13]:
df_AUM = pd.read_excel("etf_raw_daily.xlsx", sheet_name='AUM_d')

In [14]:
aum_d = pd.DataFrame(df_AUM.iloc[13:,])
aum_d = aum_d.rename(columns = df_AUM.iloc[10,1:])
aum_d = aum_d.set_index('Unnamed: 0')

friday_df_aum = aum_d[aum_d.index.weekday == 4]
friday_df_aum = friday_df_aum.astype(float).round(1)

In [15]:
etf_aum=pd.concat([universe_df,friday_df_aum.T.iloc[:,-56:]], axis=1,join ="inner")

In [16]:
stock_aum_12w = etf_aum[etf_aum['Asset']=="주식"].iloc[:,8:].sum()
bond_aum_12w = etf_aum[etf_aum['Asset']=="채권"].iloc[:,8:].sum()
commodity_aum_12w = etf_aum[etf_aum['Asset']=="원자재"].iloc[:,8:].sum()

In [17]:
asset_aum_12w = pd.concat([stock_aum_12w,bond_aum_12w,commodity_aum_12w],axis=1)
asset_aum_12w.columns = ['Stock','Bond','Commodity']

In [18]:
asset_aum_12w

                          Stock       Bond  Commodity
2024-01-12 00:00:00   7948781.3  1888642.5   223108.1
2024-01-19 00:00:00   7972716.7  1874956.1   219835.1
2024-01-26 00:00:00   8082673.5  1884002.0   219640.5
2024-02-02 00:00:00   8132512.6  1891839.0   219979.9
2024-02-09 00:00:00   8240296.8  1884468.5   218133.3
2024-02-16 00:00:00   8278632.5  1880159.8   215487.1
2024-02-23 00:00:00   8393493.2  1894820.1   216412.4
2024-03-01 00:00:00   8514701.5  1900935.1   218446.1
2024-03-08 00:00:00   8567682.3  1925289.4   228789.6
2024-03-15 00:00:00   8570176.5  1907916.9   230513.2
2024-03-22 00:00:00   8721931.5  1922025.3   231148.2
2024-03-29 00:00:00   8842588.7  1927171.3   236158.5
2024-04-05 00:00:00   8768822.6  1919703.1   246100.8
2024-04-12 00:00:00   8612898.1  1908645.7   254396.8
2024-04-19 00:00:00   8405280.4  1899104.2   251504.6
2024-04-26 00:00:00   8604996.0  1904221.1   246863.9
2024-05-03 00:00:00   8706040.3  1927802.6   241398.6
2024-05-10 00:00:00   8846821.3  1940147.2   249048.8
2024-05-17 00:00:00   9005518.9  1959093.8   254519.6
2024-05-24 00:00:00   8972601.1  1969525.1   248617.1
2024-05-31 00:00:00   8947351.3  1975590.3   249543.6
2024-06-07 00:00:00   9012038.1  1984905.7   245801.4
2024-06-14 00:00:00   9060875.5  2007368.5   246519.5
2024-06-21 00:00:00   9121820.7  2011768.6   247854.7
2024-06-28 00:00:00   9148287.5  2009527.8   248969.4
2024-07-05 00:00:00   9299329.9  2028831.0   255331.5
2024-07-12 00:00:00   9482105.3  2057963.2   257862.0
2024-07-19 00:00:00   9365852.3  2064665.9   256606.7
2024-07-26 00:00:00   9309220.5  2077182.9   255028.0
2024-08-02 00:00:00   9067217.0  2116143.8   262547.8
2024-08-09 00:00:00   9106781.5  2108461.5   257237.6
2024-08-16 00:00:00   9484467.8  2131118.1   263220.7
2024-08-23 00:00:00   9653497.7  2158546.0   267418.6
2024-08-30 00:00:00   9685290.4  2157492.3   267952.1
2024-09-06 00:00:00   9331078.9  2184686.9   266143.6
2024-09-13 00:00:00   9623707.8  2204986.1   274677.6
2024-09-20 00:00:00   9795722.0  2209789.8   278781.0
2024-09-27 00:00:00   9943791.9  2217120.1   284874.9
2024-10-04 00:00:00  10025692.6  2199211.6   285464.4
2024-10-11 00:00:00  10138952.4  2197835.3   284601.1
2024-10-18 00:00:00  10205307.2  2207445.4   292047.6
2024-10-25 00:00:00  10078491.5  2193393.4   295324.5
2024-11-01 00:00:00   9986961.0  2189224.8   295261.1
2024-11-08 00:00:00  10432701.5  2211411.7   288779.7
2024-11-15 00:00:00  10237413.4  2191773.3   275581.8
2024-11-22 00:00:00  10428730.9  2201631.6   288078.2
2024-11-29 00:00:00  10559104.0  2233724.3   283537.5
2024-12-06 00:00:00  10654825.3  2241354.1   281562.7
2024-12-13 00:00:00  10597897.4  2224892.0   282767.3
2024-12-20 00:00:00  10377580.2  2203189.3   277716.6
2024-12-27 00:00:00  10422218.5  2198028.6   277631.7
2025-01-03 00:00:00  10432229.5  2203736.0   280178.3
2025-01-10 00:00:00  10259997.9  2195877.4   285609.3
2025-01-17 00:00:00  10558900.5  2222026.5   290271.9
2025-01-24 00:00:00  10743843.6  2238746.4   294398.0
2025-01-31 00:00:00  10706569.4  2251020.6   298405.3

# FF + AUM

In [20]:
asset_ff_aum = asset_ff_12w / asset_aum_12w *100

In [21]:
asset_ff_aum = asset_ff_aum.round(2)

In [22]:
asset_ff_aum.to_csv('asset_ff_aum.csv')

# 4주 누적

In [54]:
page_4w_cul = asset_ff_12w.rolling(window=4).sum()/asset_aum_12w*100
page_4w_cul.to_csv('./data/page1_ff,aum_4w_cul.csv')

In [66]:
pd.read_csv('./data/page1_ff,aum_4w_cul.csv', index_col=0, parse_dates=True).iloc[3:]

               Stock      Bond  Commodity
2024-02-02  0.605975  1.344300  -0.845986
2024-02-09  0.941410  0.805002  -0.834811
2024-02-16  1.000020  0.700153  -0.988922
2024-02-23  0.808769  0.716374  -1.495755
2024-03-01  0.951096  0.613382  -1.417283
2024-03-08  0.848479  0.858416  -1.386427
2024-03-15  1.304326  0.878550  -0.572202
2024-03-22  1.087213  0.851185   0.236645
2024-03-29  1.090043  0.868423   0.619499
2024-04-05  1.037528  0.898576   1.147904
2024-04-12  0.356256  1.021405   0.405272
2024-04-19  0.530060  0.834920   0.026640
2024-04-26  0.324044  0.974677  -0.800846
2024-05-03  0.234469  0.948126  -1.084928
2024-05-10  0.516954  1.241194  -0.998198
2024-05-17  0.586829  1.541580  -0.413328
2024-05-24  0.566592  1.323060  -0.163706
2024-05-31  0.620496  1.229000   0.208380
2024-06-07  0.517918  1.187059   0.683072
2024-06-14  0.442816  1.093671  -0.029207
2024-06-21  0.816164  1.358059   0.400638
2024-06-28  0.886253  1.326381   0.315300
2024-07-05  0.810456  1.268169   0.353266
2024-07-12  1.089252  1.583119   0.722092
2024-07-19  1.141178  1.721683   1.023746
2024-07-26  1.080713  1.926937   1.368477
2024-08-02  1.287109  1.815614   0.978108
2024-08-09  0.938180  1.425684   0.375140
2024-08-16  0.617989  1.407008   0.049768
2024-08-23  0.680997  1.375185  -0.304018
2024-08-30  0.601851  1.453910   0.033215
2024-09-06  0.628630  1.725739   0.500106
2024-09-13  0.450221  1.732483   0.780551
2024-09-20  0.492460  1.501546   0.522632
2024-09-27  0.758182  1.405833   0.559193
2024-10-04  0.917971  1.288189   0.714275
2024-10-11  1.206121  1.112549   0.235417
2024-10-18  1.160514  1.278174   1.171384
2024-10-25  0.889468  1.125425   1.346993
2024-11-01  0.797820  1.286026   1.242968
2024-11-08  0.989983  1.393002   1.186371
2024-11-15  1.131809  1.013015  -0.288118
2024-11-22  1.142661  1.318522  -0.545685
2024-11-29  1.228599  0.981500  -0.724772
2024-12-06  0.842079  0.908870  -0.836403
2024-12-13  0.812850  1.325997  -0.458681
2024-12-20  1.320481  0.882947  -0.419852
2024-12-27  0.999720  0.950124  -0.404493
2025-01-03  1.143533  0.908094  -0.205226
2025-01-10  0.992739  0.916035   0.223382
2025-01-17  0.608615  1.269517   0.573945
2025-01-24  0.728399  1.320337   0.139947
2025-01-31  0.518420  1.345301   0.620297

# 작업

In [70]:
df_page1_bottom = pd.read_csv('./data/page1_ff,aum_4w_cul.csv', index_col=0, parse_dates=True).iloc[3:]
df_page1_bottom = round(df_page1_bottom,1)

In [84]:
df_page1_bottom = df_page1_bottom.T

In [104]:
# 데이터 변환
df_page1_bottom_processing = df_page1_bottom.reset_index().melt(id_vars="index", var_name="Date",
                                                                       value_name="ff/aum")
df_page1_bottom_processing.rename(columns={"index": "Asset"}, inplace=True)

In [106]:

# Asset 컬럼을 Categorical 타입으로 변환하여 순서 유지
asset_order = ["Commodity", "Bond", "Stock"]
df_page1_bottom_processing["Asset"] = pd.Categorical(df_page1_bottom_processing["Asset"], categories=asset_order,
                                                 ordered=True)

In [110]:
# Date 컬럼을 datetime 형식으로 변환
df_page1_bottom_processing["Date"] = pd.to_datetime(df_page1_bottom_processing["Date"])

In [112]:
 # x축 정렬을 위한 순서값 추가
df_page1_bottom_processing["DateOrder"] = range(len(df_page1_bottom_processing))
df_page1_bottom_processing["FormattedDate"] = df_page1_bottom_processing["Date"].dt.strftime("%b %d")
df_page1_bottom_processing["FormattedDate"] = pd.Categorical(
    df_page1_bottom_processing["FormattedDate"],
    categories=df_page1_bottom_processing.sort_values("DateOrder")["FormattedDate"].unique(),
    ordered=True
)

In [116]:
# 색상 설정
colorscale = [[0, "#ffffff"], [0.5, "#c6dbef"], [1, "#084594"]]

In [120]:
pivot_table_4w = df_page1_bottom_processing.pivot(index="Asset", columns="FormattedDate", values="ff/aum").loc[asset_order]

In [ ]:
# Plotly 히트맵 생성
page1_bottom = go.Figure()
page1_bottom.add_trace(go.Heatmap(
    z=pivot_table_4w.values,
    x=pivot_table_4w.columns,
    y=pivot_table_4w.index,
    colorscale=colorscale,
    showscale=True,
    colorbar=dict(title="FundFlow(4-week cumulative)/AUM(%)", tickfont=dict(size=10, family="Arial"), outlinewidth=0),
    hovertemplate="Date: %{x}<br>Asset: %{y}<br>FF/AUM(%): %{z:.2f}<extra></extra>",
))

# 숫자 데이터 라벨 추가
for i, row in enumerate(pivot_table_4w.index):
    for j, col in enumerate(pivot_table_4w.columns):
        page1_col2.add_trace(go.Scatter(
            x=[col],
            y=[row],
            text=[f"{pivot_table_4w.loc[row, col]:.1f}"],
            mode="text",
            textfont=dict(size=12, family="Arial", color="#1C1C1C"),
            showlegend=False
        ))

# 히트맵 레이아웃 조정
page1_bottom.update_layout(
    title="Asset Return(weekly)",
    title_font=dict(size=30, family="Arial", color="#084594"),
    xaxis=dict(title="", tickfont=dict(size=12, family="Arial")),
    yaxis=dict(title="", tickfont=dict(size=12, family="Arial")),
    plot_bgcolor="white",
    margin=dict(l=10, r=10, t=60, b=10),

)
with st.container():
    # col2에 히트맵 추가
    st.plotly_chart(page1_bottom, use_container_width=True)

In [90]:

# 데이터 로드 함수
@st.cache_data
def load_data_page1_col2():
    df = pd.read_csv("data/asset_return_weekly.csv", index_col=0, parse_dates=True)
    return df


# 데이터 불러오기
df_page1_col2 = load_data_page1_col2()
df_page1_col2 = round(df_page1_col2, 2)

# 최근 12주 데이터 필터링
filtered_df_page1_col2 = df_page1_col2.tail(12).T
filtered_df_page1_col2 = filtered_df_page1_col2.loc[["Stock", "Bond", "Commodity"], :]

2025-02-07 15:44:12.454 No runtime found, using MemoryCacheStorageManager

In [92]:
filtered_df_page1_col2

Unnamed: 0,2024-11-15,2024-11-22,2024-11-29,2024-12-06,2024-12-13,2024-12-20,2024-12-27,2025-01-03,2025-01-10,2025-01-17,2025-01-24,2025-01-31
Stock,-2.36,1.37,0.98,1.30,-0.87,-2.53,0.88,-0.52,-1.58,2.56,2.07,-0.44
Bond,-0.84,0.19,1.39,0.45,-1.38,-0.69,-0.33,0.18,-0.87,0.99,0.11,0.44
Commodity,-2.09,3.80,-2.10,-0.79,2.79,-1.32,0.76,1.93,3.13,1.22,-1.18,-1.62

In [86]:
# 데이터 변환
filtered_df_page1_col2 = filtered_df_page1_col2.reset_index().melt(id_vars="index", var_name="Date",
                                                                       value_name="Return")

In [98]:
filtered_df_page1_col2

Unnamed: 0,2024-11-15,2024-11-22,2024-11-29,2024-12-06,2024-12-13,2024-12-20,2024-12-27,2025-01-03,2025-01-10,2025-01-17,2025-01-24,2025-01-31
Stock,-2.36,1.37,0.98,1.30,-0.87,-2.53,0.88,-0.52,-1.58,2.56,2.07,-0.44
Bond,-0.84,0.19,1.39,0.45,-1.38,-0.69,-0.33,0.18,-0.87,0.99,0.11,0.44
Commodity,-2.09,3.80,-2.10,-0.79,2.79,-1.32,0.76,1.93,3.13,1.22,-1.18,-1.62

In [100]:
filtered_df_page1_col2.rename(columns={"index": "Asset"}, inplace=True)

In [102]:
filtered_df_page1_col2

Unnamed: 0,2024-11-15,2024-11-22,2024-11-29,2024-12-06,2024-12-13,2024-12-20,2024-12-27,2025-01-03,2025-01-10,2025-01-17,2025-01-24,2025-01-31
Stock,-2.36,1.37,0.98,1.30,-0.87,-2.53,0.88,-0.52,-1.58,2.56,2.07,-0.44
Bond,-0.84,0.19,1.39,0.45,-1.38,-0.69,-0.33,0.18,-0.87,0.99,0.11,0.44
Commodity,-2.09,3.80,-2.10,-0.79,2.79,-1.32,0.76,1.93,3.13,1.22,-1.18,-1.62