In [1]:
import pandas as pd

# 엑셀 파일 불러오기 (sheet_name으로 특정 시트 지정 가능)
df_raw = pd.read_excel("etf_raw_daily.xlsx", sheet_name='FF_d')

In [2]:
ff_d = pd.DataFrame(df_raw.iloc[13:,])
ff_d = ff_d.rename( columns = df_raw.iloc[10,1:])
ff_d = ff_d.set_index('Unnamed: 0')
ff_d

,SPY US Equity,VOO US Equity,IVV US Equity,VTI US Equity,QQQ US Equity,VUG US Equity,1306 JP Equity,VEA US Equity,VTV US Equity,IEFA US Equity,...,ENCO LN Equity,CCUSAS SW Equity,AAAU US Equity,BAR US Equity,USO US Equity,DBA US Equity,ROLL LN Equity,CGL CN Equity,ZGOLD TI Equity,XGDE GR Equity
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
2019-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-30,224.7472,55.2044,-48.3705,-96.9306,-190.9156,15.8744,-0.0147,0.534,20.4527,0,...,NaN,0,0,0,40.0303,0,0,0,NaN,NaN
2019-12-31,4572.9244,20.2073,-97.032,163.3729,148.8862,15.5704,NaN,0.2451,37.0816,0,...,NaN,0,0,0,-52.4127,0,0,0,NaN,NaN
2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-27,6141.6511,-56.5979,-240.8267,66.3541,4342.9273,-9.5818,-0.1605,0.472,-8.6908,0,...,0,0,0,0,179.5089,0,18.4209,0,0,0
2025-01-28,-3295.6286,870.5774,-2430.4577,-27.5649,-2427.8609,48.8735,37.3446,0.5818,51.7528,0,...,-0.419,0,0,0,7.8694,0,0.7641,0,0,0
2025-01-29,-30.0939,455.8879,-1028.1164,148.9077,-1458.4165,158.1184,0,1.5758,58.6136,0,...,0,0,9.5358,0,-30.9899,0,1.535,3.7706,0,1.1816
2025-01-30,-2813.5169,-653.4532,1884.7172,144.2026,444.7298,32.476,0,0.1419,98.1612,0,...,-1.8148,0,0,0,15.5198,0,0,0,0,0
2025-01-31,-3341.3456,891.1122,120.9886,178.9666,-1619.8287,41.8794,0.0683,0.733,208.1766,0,...,NaN,NaN,0,0,-30.9572,2.7586,0,0,0,NaN

In [3]:
ff_d_to_w = ff_d.resample('W-FRI').sum()

In [4]:
universe_df = pd.read_csv('universe.csv', index_col=0)
universe_df = universe_df.set_index('Full_ticker')

KeyError: "None of ['Full_ticker'] are in the columns"

In [ ]:
etf_ff = pd.concat([universe_df,ff_d_to_w.T.iloc[:,-36:]], axis=1,join ="inner")
etf_ff

In [ ]:
stock_ff_12w = etf_ff[etf_ff['Asset']=="주식"].iloc[:,8:].sum()
bond_ff_12w = etf_ff[etf_ff['Asset']=="채권"].iloc[:,8:].sum()
commodity_ff_12w = etf_ff[etf_ff['Asset']=="원자재"].iloc[:,8:].sum()

In [ ]:
asset_ff_12w = pd.concat([stock_ff_12w,bond_ff_12w,commodity_ff_12w],axis=1)

In [ ]:
asset_ff_12w.columns = ['Stock','Bond','Commodity']

In [ ]:
asset_ff_12w = asset_ff_12w.astype(int)
asset_ff_12w

In [ ]:
asset_ff_12w.to_csv('asset_ff_12w.csv')

# AUM_timeseries

In [ ]:
df_AUM = pd.read_excel("etf_raw_daily.xlsx", sheet_name='AUM_d')

In [ ]:
aum_d = pd.DataFrame(df_AUM.iloc[13:,])
aum_d = aum_d.rename(columns = df_AUM.iloc[10,1:])
aum_d = aum_d.set_index('Unnamed: 0')

friday_df_aum = aum_d[aum_d.index.weekday == 4]
friday_df_aum = friday_df_aum.astype(float).round(1)

In [ ]:
etf_aum=pd.concat([universe_df,friday_df_aum.T.iloc[:,-36:]], axis=1,join ="inner")

In [ ]:
stock_aum_12w = etf_aum[etf_aum['Asset']=="주식"].iloc[:,8:].sum()
bond_aum_12w = etf_aum[etf_aum['Asset']=="채권"].iloc[:,8:].sum()
commodity_aum_12w = etf_aum[etf_aum['Asset']=="원자재"].iloc[:,8:].sum()

In [ ]:
asset_aum_12w = pd.concat([stock_aum_12w,bond_aum_12w,commodity_aum_12w],axis=1)
asset_aum_12w.columns = ['Stock','Bond','Commodity']

In [ ]:
asset_aum_12w

# FF + AUM

In [ ]:
asset_ff_aum = asset_ff_12w / asset_aum_12w *100

In [ ]:
asset_ff_aum = asset_ff_aum.round(2)

In [ ]:
asset_ff_aum.to_csv('asset_ff_aum.csv')