In [1]:
import pandas as pd

# 엑셀 파일 불러오기 (sheet_name으로 특정 시트 지정 가능)
df_raw = pd.read_excel("etf_raw_daily.xlsx", sheet_name=None)
df_universe = pd.read_excel('etf_classification.xlsx', sheet_name='classification_raw')

C:\Users\USER\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:81: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():
C:\Users\USER\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:81: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

## UNIVERSE

In [3]:
universe = pd.DataFrame(df_universe.iloc[1:,0:10])
universe.columns = df_universe.iloc[0,0:10]
# universe = universe.iloc[:,1:]
# universe.columns = [     'NAME',    'Ticker',       'AUM',     'Asset', 'Strategy1',
#        'Strategy2', 'Strategy3',       'AUM2',         'Full_ticker']
# universe = universe[['Full_ticker','NAME',    'Ticker',       'AUM',     'Asset', 'Strategy1',
#        'Strategy2', 'Strategy3',       'AUM2']]
universe = universe.drop(columns='AUM')

In [4]:
universe.to_csv('universe.csv')

## fundflow

In [6]:
ff_d = pd.DataFrame(df_raw['FF_d'].iloc[13:,])
ff_d = ff_d.rename( columns = df_raw['FF_d'].iloc[10,1:])
ff_d = ff_d.set_index('Unnamed: 0')
ff_d

,SPY US Equity,VOO US Equity,IVV US Equity,VTI US Equity,QQQ US Equity,VUG US Equity,1306 JP Equity,VEA US Equity,VTV US Equity,IEFA US Equity,...,ENCO LN Equity,CCUSAS SW Equity,AAAU US Equity,BAR US Equity,USO US Equity,DBA US Equity,ROLL LN Equity,CGL CN Equity,ZGOLD TI Equity,XGDE GR Equity
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
2019-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-30,224.7472,55.2044,-48.3705,-96.9306,-190.9156,15.8744,-0.0147,0.534,20.4527,0,...,NaN,0,0,0,40.0303,0,0,0,NaN,NaN
2019-12-31,4572.9244,20.2073,-97.032,163.3729,148.8862,15.5704,NaN,0.2451,37.0816,0,...,NaN,0,0,0,-52.4127,0,0,0,NaN,NaN
2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-27,6141.6511,-56.5979,-240.8267,66.3541,4342.9273,-9.5818,-0.1605,0.472,-8.6908,0,...,0,0,0,0,179.5089,0,18.4209,0,0,0
2025-01-28,-3295.6286,870.5774,-2430.4577,-27.5649,-2427.8609,48.8735,37.3446,0.5818,51.7528,0,...,-0.419,0,0,0,7.8694,0,0.7641,0,0,0
2025-01-29,-30.0939,455.8879,-1028.1164,148.9077,-1458.4165,158.1184,0,1.5758,58.6136,0,...,0,0,9.5358,0,-30.9899,0,1.535,3.7706,0,1.1816
2025-01-30,-2813.5169,-653.4532,NaN,144.2026,444.7298,32.476,-0.1752,0.1419,98.1612,NaN,...,NaN,NaN,0,0,15.5198,0,0,0,0,NaN
2025-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
ff_d_to_w = ff_d.resample('W-FRI').sum()

In [8]:
ff_d_to_w.iloc[-1].to_csv('ff_w_recently.csv')

## aum

In [10]:
aum_d = pd.DataFrame(df_raw['AUM_d'].iloc[13:,])
aum_d = aum_d.rename( columns = df_raw['AUM_d'].iloc[10,1:])
aum_d = aum_d.set_index('Unnamed: 0')
aum_d

,SPY US Equity,VOO US Equity,IVV US Equity,VTI US Equity,QQQ US Equity,VUG US Equity,1306 JP Equity,VEA US Equity,VTV US Equity,IEFA US Equity,...,ENCO LN Equity,CCUSAS SW Equity,AAAU US Equity,BAR US Equity,USO US Equity,DBA US Equity,ROLL LN Equity,CGL CN Equity,ZGOLD TI Equity,XGDE GR Equity
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
2019-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-30,307394.5953,130177.9395,200804.8232,137537.7776,87025.7107,46319.3556,100784.7093,78516.8751,55622.6235,74004.7385,...,NaN,1059.5436,175.2751,589.7174,1261.599,347.7341,106.535,476.85288,NaN,NaN
2019-12-31,311967.5198,130586.4874,201311.6576,138114.0757,87066.5431,46467.4198,NaN,78749.8954,55841.2198,74045.3951,...,NaN,1062.3466,176.228,592.9269,1196.5428,347.7926,105.9081,481.26236,NaN,NaN
2020-01-01,314620.1052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-27,636589.7364,616964.4262,599568.2855,471773.186,326308.8341,157842.2617,151727.0889,139523.7607,135375.1431,123059.5626,...,2012.6253,1602.5216,941.5177,889.108,1063.2859,848.0377,824.5353,1055.96383,796.90717,773.41906
2025-01-28,630335.3754,623523.5822,602662.3704,475922.5728,329064.7101,161485.7598,150421.5398,139524.3424,134450.8345,123014.0709,...,2020.7931,1598.0797,944.775,892.1841,1079.972,856.3546,827.8285,1059.81458,796.88781,771.55758
2025-01-29,633635.5416,621063.9221,598817.3137,474006.9472,326813.7164,160630.1932,151979.4987,139497.935,134242.4535,123009.3597,...,2028.2496,1607.1581,955.8169,893.6065,1032.244,869.4536,833.0379,1070.21605,805.85034,773.41257
2025-01-30,630822.0247,623698.4807,603869.4574,477026.5187,328732.0224,160831.145,153078.0192,141037.1714,135737.2246,124433.6848,...,NaN,NaN,966.5464,903.6377,1049.4199,862.7172,835.7921,1082.01119,819.09018,NaN
2025-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
aum_d_to_w = aum_d.ffill().resample('W-FRI').ffill()

C:\Users\USER\AppData\Local\Temp\ipykernel_1628\2989770733.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  aum_d_to_w = aum_d.ffill().resample('W-FRI').ffill()

In [12]:
aum_d_to_w.iloc[-1].to_csv('aum_w_recently.csv')

## 데이터 합치기

In [14]:
pd.read_csv('universe.csv', index_col=0)

,Full_ticker,NAME,Ticker,Asset,Strategy1,Strategy2,Strategy3,DM/EM,Country
1,SPY US Equity,SPDR S&P 500 ETF Trust,SPY US,주식,Blend,Large,NaN,DM,US
2,VOO US Equity,Vanguard S&P 500 ETF,VOO US,주식,Blend,Large,NaN,DM,US
3,IVV US Equity,iShares Core S&P 500 ETF,IVV US,주식,Blend,Large,NaN,DM,US
4,VTI US Equity,Vanguard Total Stock Market ETF,VTI US,주식,Blend,NaN,NaN,DM,US
5,QQQ US Equity,Invesco QQQ Trust Series 1,QQQ US,주식,Growth,Large,NaN,DM,US
...,...,...,...,...,...,...,...,...,...
11056,CXAS LN Equity,UBS ETC linked to UBS Bloomberg CMCI ex-Agri e...,CXAS LN,원자재,diversified,NaN,NaN,NaN,NaN
11057,BCHOUU SW Equity,UBS ETC linked to the Bloomberg Heating Oil Su...,BCHOUU SW,원자재,energy_commodity,NaN,NaN,NaN,NaN
11058,BCLSUU SW Equity,UBS ETC linked to the Bloomberg Livestock Subi...,BCLSUU SW,원자재,livestock,NaN,NaN,NaN,NaN
11059,BCSUUU SW Equity,UBS ETC linked to the Bloomberg Sugar Subindex...,BCSUUU SW,원자재,agriculture,NaN,NaN,NaN,NaN
11060,EPLCIU SW Equity,UBS ETC on UBS Bloomberg CMCI Platinum EUR Mon...,EPLCIU SW,원자재,energy_commodity,NaN,NaN,NaN,NaN

In [15]:
universe_df = pd.read_csv('universe.csv', index_col=0)
universe_df = universe_df.set_index('Full_ticker')
ff_w_df = pd.read_csv('ff_w_recently.csv', index_col=0)
aum_w_df = pd.read_csv('aum_w_recently.csv', index_col=0)

In [16]:
df = pd.concat([universe_df, ff_w_df, aum_w_df], axis= 1, join ="inner",ignore_index = True)

In [17]:
df

,0,1,2,3,4,5,6,7,8,9
SPY US Equity,SPDR S&P 500 ETF Trust,SPY US,주식,Blend,Large,NaN,DM,US,2.4117,630822.02470
VOO US Equity,Vanguard S&P 500 ETF,VOO US,주식,Blend,Large,NaN,DM,US,616.4142,623698.48070
IVV US Equity,iShares Core S&P 500 ETF,IVV US,주식,Blend,Large,NaN,DM,US,-3699.4008,603869.45740
VTI US Equity,Vanguard Total Stock Market ETF,VTI US,주식,Blend,NaN,NaN,DM,US,331.8995,477026.51870
QQQ US Equity,Invesco QQQ Trust Series 1,QQQ US,주식,Growth,Large,NaN,DM,US,901.3797,328732.02240
...,...,...,...,...,...,...,...,...,...,...
DBA US Equity,Invesco DB Agriculture Fund,DBA US,원자재,agriculture,NaN,NaN,NaN,NaN,0.0000,862.71720
ROLL LN Equity,iShares Bloomberg Enhanced Roll Yield Commodit...,ROLL LN,원자재,diversified,NaN,NaN,NaN,NaN,20.7200,835.79210
CGL CN Equity,iShares Gold Bullion ETF,CGL CN,원자재,Precious_metals,NaN,NaN,NaN,NaN,3.7706,1082.01119
ZGOLD TI Equity,Ziraat Portfoy Gold Participation ETF,ZGOLD TI,원자재,Precious_metals,NaN,NaN,NaN,NaN,0.0000,819.09018
XGDE GR Equity,Xtrackers IE Physical Gold EUR Hedged ETC Secu...,XGDE GR,원자재,Precious_metals,NaN,NaN,NaN,NaN,1.1816,773.41257

In [18]:
df = df[[0,9,8,2,3,4,5,6,7]]
df.columns = ['name','aum','ff','asset','Strategy1', 'Strategy2','Strategy3','DM/EM','Country']

In [19]:
df['aum'] = df['aum'].fillna(0)
df['ff'] = df['ff'].fillna(0)

C:\Users\USER\AppData\Local\Temp\ipykernel_1628\3584040796.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['aum'] = df['aum'].fillna(0)
C:\Users\USER\AppData\Local\Temp\ipykernel_1628\3584040796.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ff'] = df['ff'].fillna(0)

In [20]:
df.to_csv('data.csv')

# 자산군 분류별 전처리

In [22]:
# Fund Flow를 자산유형(asset)과 스타일1(c1) 기준으로 합산
fund_flow_summary1 = df.groupby(['asset', 'Strategy1'])[['ff','aum']].sum().reset_index()
fund_flow_summary2 = df.groupby(['asset', 'Strategy2'])[['ff','aum']].sum().reset_index()
fund_flow_summary3 = df.groupby(['asset', 'Strategy3'])[['ff','aum']].sum().reset_index()
fund_flow_summary4 = df.groupby(['asset', 'DM/EM'])[['ff','aum']].sum().reset_index()
fund_flow_summary5 = df.groupby(['asset', 'Country'])[['ff','aum']].sum().reset_index()

In [23]:
fund_flow_summary1.columns = ['자산군','분류','Fund_Flow','AUM']
fund_flow_summary2.columns = ['자산군','분류','Fund_Flow','AUM']
fund_flow_summary3.columns = ['자산군','분류','Fund_Flow','AUM']
fund_flow_summary4.columns = ['자산군','분류','Fund_Flow','AUM']
fund_flow_summary5.columns = ['자산군','분류','Fund_Flow','AUM']

In [24]:
fund_flow_df = pd.concat([fund_flow_summary1,fund_flow_summary2,fund_flow_summary3,fund_flow_summary4,fund_flow_summary5],axis=0)
fund_flow_df = fund_flow_df.round(1)
fund_flow_df

    자산군                분류  Fund_Flow        AUM
0    대체      equity_hedge       33.8     1876.8
1    대체             macro     -202.0   166179.0
2    대체    multi_strategy        3.2      700.2
3   원자재   Precious_metals      952.8   272217.2
4   원자재       agriculture        0.0      862.7
5   원자재       diversified      -41.1    20337.2
6   원자재  energy_commodity      171.9     1049.4
7   원자재  industrial_metal        7.8     1229.4
8    주식             Blend     4291.2  8012855.1
9    주식            Growth     5570.5  1558479.1
10   주식             Value     2104.6  1133575.1
11   채권               agg     1620.0   744722.8
12   채권        asset_back     1184.4    25378.3
13   채권         bank_loan      987.6    27015.4
14   채권       convertible       43.2    13395.8
15   채권         corporate     1417.4   575063.1
16   채권        government      562.6   671534.7
17   채권         inflation      205.1    68344.6
18   채권      mortage_back      724.7    78825.8
19   채권          prefered       32.0    38997.5
0    주식             Large     7236.4  7433318.1
1    주식               mid      201.6   435835.1
2    주식             small      412.3   518515.2
3    채권                A+     2148.2   613557.2
4    채권                HY      931.4   123865.7
5    채권                IG     1673.2  1153550.8
0    주식     Communication      197.3    38876.9
1    주식     discretionary      477.5    39071.6
2    주식            energy     -287.1    70512.0
3    주식         financial     1701.1   116225.1
4    주식        healthcare      236.0    98345.1
5    주식        industrial      974.9    55203.3
6    주식         materials     -256.9    37810.6
7    주식           staples     -101.1    25559.2
8    주식        technology     2501.8   389806.0
9    주식         utilities     -305.4    31479.3
10   채권      intermediate      339.5   355094.0
11   채권              long      858.5   243241.6
12   채권             short      844.1   322114.1
0    주식                DM    12133.6  8846903.2
1    주식                EM     -957.9   831885.4
0    주식             China     -757.9   321489.6
1    주식            Europe      207.8   131737.5
2    주식             Japan      962.9   597377.4
3    주식             Korea        0.0    10421.0
4    주식            Taiwan        0.0    77001.8
5    주식                US     6138.2  4809747.0
6    주식             india     -224.6    83057.2

In [25]:
asset_order = ['주식','채권','원자재','대체']
calssification_order =['DM',
                       'EM',
                       'US',
                       'Europe',
                       'Japan',
                       'China',
                       'Taiwan',
                       'Korea',
                       'india',
                       'Growth',
                       'Value',
                       'Large',
                       'mid',
                       'small',                
                       'Communication',
                       'discretionary',
                       'staples',
                       'energy',
                       'financial',
                       'healthcare',
                       'industrial',
                       'materials',
                       'technology',
                       'utilities',
                       'agg',
                       'bank_loan',
                       'convertible',
                       'corporate',
                       'government',
                       'inflation',
                       'mortage_back',
                       'A+',
                       'IG',
                       'HY',
                       'long',
                       'intermediate',
                       'short',
                       'diversified',
                       'Precious_metals',
                       'energy_commodity',
                       'industrial_metal',
                       'agriculture',
                       'multi_strategy',
                       'macro',
                       'equity_hedge']

fund_flow_df['자산군'] = pd.Categorical(fund_flow_df['자산군'], categories=asset_order, ordered=True)
fund_flow_df['분류'] = pd.Categorical(fund_flow_df['분류'], categories=calssification_order, ordered=True)

# # 정렬 수행
fund_flow_df_sorted = fund_flow_df.sort_values(by=['자산군','분류'])

In [26]:
fund_flow_df_sorted['ff/aum']= round(fund_flow_df_sorted['Fund_Flow']/fund_flow_df_sorted['AUM']*100,2)
fund_flow_df_sorted = fund_flow_df_sorted.dropna(subset=["분류"])

### 분류 네임 맞추기

In [28]:
name_new_list = df_raw['BM'].iloc[5:53,11].dropna().to_list()

In [29]:
fund_flow_df_sorted['분류'] = name_new_list

In [30]:
fund_flow_df_sorted

    자산군                   분류  Fund_Flow        AUM  ff/aum
0    주식                   DM    12133.6  8846903.2    0.14
1    주식                   EM     -957.9   831885.4   -0.12
5    주식                   US     6138.2  4809747.0    0.13
1    주식               Europe      207.8   131737.5    0.16
2    주식                Japan      962.9   597377.4    0.16
0    주식                China     -757.9   321489.6   -0.24
4    주식               Taiwan        0.0    77001.8    0.00
3    주식                Korea        0.0    10421.0    0.00
6    주식                India     -224.6    83057.2   -0.27
9    주식               Growth     5570.5  1558479.1    0.36
10   주식                Value     2104.6  1133575.1    0.19
0    주식                Large     7236.4  7433318.1    0.10
1    주식                  Mid      201.6   435835.1    0.05
2    주식                Small      412.3   518515.2    0.08
0    주식        Communication      197.3    38876.9    0.51
1    주식        Discretionary      477.5    39071.6    1.22
7    주식              Staples     -101.1    25559.2   -0.40
2    주식               Energy     -287.1    70512.0   -0.41
3    주식            Financial     1701.1   116225.1    1.46
4    주식           Healthcare      236.0    98345.1    0.24
5    주식           Industrial      974.9    55203.3    1.77
6    주식            Materials     -256.9    37810.6   -0.68
8    주식           Technology     2501.8   389806.0    0.64
9    주식             Utilites     -305.4    31479.3   -0.97
11   채권                  Agg     1620.0   744722.8    0.22
13   채권            Bank_loan      987.6    27015.4    3.66
14   채권          Convertible       43.2    13395.8    0.32
15   채권            Corporate     1417.4   575063.1    0.25
16   채권           Government      562.6   671534.7    0.08
17   채권  Inflation_protected      205.1    68344.6    0.30
18   채권      Mortgage_Backed      724.7    78825.8    0.92
3    채권              A_above     2148.2   613557.2    0.35
5    채권                   IG     1673.2  1153550.8    0.15
4    채권                   HY      931.4   123865.7    0.75
11   채권                 Long      858.5   243241.6    0.35
10   채권         Intermediate      339.5   355094.0    0.10
12   채권                  Low      844.1   322114.1    0.26
5   원자재          Diversified      -41.1    20337.2   -0.20
3   원자재      Precious_metals      952.8   272217.2    0.35
6   원자재          Energy&Fuel      171.9     1049.4   16.38
7   원자재    Industrial_metals        7.8     1229.4    0.63
4   원자재          Agriculture        0.0      862.7    0.00
2    대체       multi_strategy        3.2      700.2    0.46
1    대체                macro     -202.0   166179.0   -0.12
0    대체         equity_hedge       33.8     1876.8    1.80

In [31]:
fund_flow_df_sorted.to_csv('asset_ff,aum.csv',encoding='utf-8-sig', index=False)

## 자산군별 수익률 데이터

In [33]:
df_price = pd.DataFrame(df_raw['asset_price'].iloc[16:,])
df_price = df_price.rename(columns=df_raw['asset_price'].iloc[12,1:49])

In [34]:
df_price.set_index('Unnamed: 0', inplace=True)

In [35]:
return_1w = round(df_price.pct_change(periods=7)*100,1)
return_1m = round(df_price.pct_change(periods=30)*100,1)

C:\Users\USER\AppData\Local\Temp\ipykernel_1628\2361069769.py:1: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_1w = round(df_price.pct_change(periods=7)*100,1)
C:\Users\USER\AppData\Local\Temp\ipykernel_1628\2361069769.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  return_1w = round(df_price.pct_change(periods=7)*100,1)
C:\Users\USER\AppData\Local\Temp\ipykernel_1628\2361069769.py:2: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_1m = round(df_price.pct_change(periods=30)*100,1)
C:\Users\USER\AppData\Local\Temp\ipykernel_1628\2361069769.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  return_1m = round(df_price.pct_change(periods=30)*100,1)

In [36]:
fund_flow_df_sorted['return_1w'] = fund_flow_df_sorted['분류'].map(return_1w.iloc[-1])
fund_flow_df_sorted['return_1m'] = fund_flow_df_sorted['분류'].map(return_1m.iloc[-1])

In [46]:
new_order = ['자산군','분류','AUM','Fund_Flow','ff/aum','return_1w','return_1m']
fund_flow_df_sorted = fund_flow_df_sorted[new_order]

In [48]:
fund_flow_df_sorted.to_csv('asset_ff,aum.csv',encoding='utf-8-sig', index=False)

In [54]:
pd.read_csv("asset_ff,aum.csv")

,자산군,분류,AUM,Fund_Flow,ff/aum,return_1w,return_1m
0,주식,DM,8846903.2,12133.6,0.14,-0.1,3.9
1,주식,EM,831885.4,-957.9,-0.12,0.5,1.8
2,주식,US,4809747.0,6138.2,0.13,-0.5,3.2
3,주식,Europe,131737.5,207.8,0.16,1.7,6.2
4,주식,Japan,597377.4,962.9,0.16,-0.9,-0.8
5,주식,China,321489.6,-757.9,-0.24,-0.4,-3.0
6,주식,Taiwan,77001.8,0.0,0.00,0.0,3.0
7,주식,Korea,10421.0,0.0,0.00,-0.8,4.9
8,주식,India,83057.2,-224.6,-0.27,1.4,-1.6
9,주식,Growth,1558479.1,5570.5,0.36,-0.9,2.9
10,주식,Value,1133575.1,2104.6,0.19,0.9,4.7
11,주식,Large,7433318.1,7236.4,0.10,-0.1,3.6
12,주식,Mid,435835.1,201.6,0.05,0.3,4.4
13,주식,Small,518515.2,412.3,0.08,0.3,3.1
14,주식,Communication,38876.9,197.3,0.51,-4.2,2.5
15,주식,Discretionary,39071.6,477.5,1.22,1.1,4.3
16,주식,Staples,25559.2,-101.1,-0.40,2.4,2.4
17,주식,Energy,70512.0,-287.1,-0.41,-0.8,4.3
18,주식,Financial,116225.1,1701.1,1.46,1.5,6.3
19,주식,Healthcare,98345.1,236.0,0.24,1.8,6.4
20,주식,Industrial,55203.3,974.9,1.77,-1.2,4.7
21,주식,Materials,37810.6,-256.9,-0.68,0.2,5.5
22,주식,Technology,389806.0,2501.8,0.64,-2.9,-0.5
23,주식,Utilites,31479.3,-305.4,-0.97,-0.4,2.2
24,채권,Agg,744722.8,1620.0,0.22,0.6,0.7
25,채권,Bank_loan,27015.4,987.6,3.66,-0.0,0.7
26,채권,Convertible,13395.8,43.2,0.32,0.1,3.4
27,채권,Corporate,575063.1,1417.4,0.25,0.3,0.6
28,채권,Government,671534.7,562.6,0.08,0.3,0.8
29,채권,Inflation_protected,68344.6,205.1,0.30,0.6,1.2
30,채권,Mortgage_Backed,78825.8,724.7,0.92,0.7,0.7
31,채권,A_above,613557.2,2148.2,0.35,1.3,1.2
32,채권,IG,1153550.8,1673.2,0.15,0.6,0.8
33,채권,HY,123865.7,931.4,0.75,0.2,1.5
34,채권,Long,243241.6,858.5,0.35,1.3,1.2
35,채권,Intermediate,355094.0,339.5,0.10,0.8,0.8
36,채권,Low,322114.1,844.1,0.26,0.2,0.4
37,원자재,Diversified,20337.2,-41.1,-0.20,-0.5,4.5
38,원자재,Precious_metals,272217.2,952.8,0.35,1.6,8.0
39,원자재,Energy&Fuel,1049.4,171.9,16.38,-1.8,2.2
40,원자재,Industrial_metals,1229.4,7.8,0.63,-1.1,2.6
41,원자재,Agriculture,862.7,0.0,0.00,1.6,4.9
42,대체,multi_strategy,700.2,3.2,0.46,0.3,2.1
43,대체,macro,166179.0,-202.0,-0.12,0.2,11.6
44,대체,equity_hedge,1876.8,33.8,1.80,NaN,NaN