In [1]:
import pandas as pd

# 엑셀 파일 불러오기 (sheet_name으로 특정 시트 지정 가능)
df_raw = pd.read_excel("etf_raw_daily.xlsx", sheet_name=None)
df_universe = pd.read_excel('etf_classification.xlsx', sheet_name='classification_raw')

C:\Users\USER\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:81: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():
C:\Users\USER\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:81: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

## UNIVERSE

In [3]:
universe = pd.DataFrame(df_universe.iloc[1:,0:10])
universe.columns = df_universe.iloc[0,0:10]
# universe = universe.iloc[:,1:]
# universe.columns = [     'NAME',    'Ticker',       'AUM',     'Asset', 'Strategy1',
#        'Strategy2', 'Strategy3',       'AUM2',         'Full_ticker']
# universe = universe[['Full_ticker','NAME',    'Ticker',       'AUM',     'Asset', 'Strategy1',
#        'Strategy2', 'Strate`gy3',       'AUM2']]
universe = universe.drop(columns='AUM')

In [4]:
universe.to_csv('universe.csv',encoding='utf-8-sig', index=False)

## fundflow

In [6]:
ff_d = pd.DataFrame(df_raw['FF_d'].iloc[13:,])
ff_d = ff_d.rename( columns = df_raw['FF_d'].iloc[10,1:])
ff_d = ff_d.set_index('Unnamed: 0')
ff_d

,SPY US Equity,VOO US Equity,IVV US Equity,VTI US Equity,QQQ US Equity,VUG US Equity,1306 JP Equity,VEA US Equity,VTV US Equity,IEFA US Equity,...,ENCO LN Equity,CCUSAS SW Equity,AAAU US Equity,BAR US Equity,USO US Equity,DBA US Equity,ROLL LN Equity,CGL CN Equity,ZGOLD TI Equity,XGDE GR Equity
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
2019-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-30,224.7472,55.2044,-48.3705,-96.9306,-190.9156,15.8744,-0.0147,0.534,20.4527,0,...,NaN,0,0,0,40.0303,0,0,0,NaN,NaN
2019-12-31,4572.9244,20.2073,-97.032,163.3729,148.8862,15.5704,NaN,0.2451,37.0816,0,...,NaN,0,0,0,-52.4127,0,0,0,NaN,NaN
2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-27,6141.6511,-56.5979,-240.8267,66.3541,4342.9273,-9.5818,-0.1605,0.472,-8.6908,0,...,0,0,0,0,179.5089,0,18.4209,0,0,0
2025-01-28,-3295.6286,870.5774,-2430.4577,-27.5649,-2427.8609,48.8735,37.3446,0.5818,51.7528,0,...,-0.419,0,0,0,7.8694,0,0.7641,0,0,0
2025-01-29,-30.0939,455.8879,-1028.1164,148.9077,-1458.4165,158.1184,0,1.5758,58.6136,0,...,0,0,9.5358,0,-30.9899,0,1.535,3.7706,0,1.1816
2025-01-30,-2813.5169,-653.4532,1884.7172,144.2026,444.7298,32.476,0,0.1419,98.1612,0,...,-1.8148,0,0,0,15.5198,0,0,0,0,0
2025-01-31,-3341.3456,891.1122,120.9886,178.9666,-1619.8287,41.8794,0.0683,0.733,208.1766,0,...,NaN,NaN,0,0,-30.9572,2.7586,0,0,0,NaN

In [7]:
ff_d_to_w = ff_d.resample('W-FRI').sum()

In [8]:
ff_d_to_w.iloc[-1].to_csv('ff_w_recently.csv')

## aum

In [10]:
aum_d = pd.DataFrame(df_raw['AUM_d'].iloc[13:,])
aum_d = aum_d.rename( columns = df_raw['AUM_d'].iloc[10,1:])
aum_d = aum_d.set_index('Unnamed: 0')
aum_d

,SPY US Equity,VOO US Equity,IVV US Equity,VTI US Equity,QQQ US Equity,VUG US Equity,1306 JP Equity,VEA US Equity,VTV US Equity,IEFA US Equity,...,ENCO LN Equity,CCUSAS SW Equity,AAAU US Equity,BAR US Equity,USO US Equity,DBA US Equity,ROLL LN Equity,CGL CN Equity,ZGOLD TI Equity,XGDE GR Equity
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
2019-12-28,306244.474,130859.387,201994.7663,138376.8107,87750.6643,46629.5082,100930.7727,78981.8883,55867.364,74234.5589,...,NaN,1056.3412,174.8999,588.4604,1222.2517,347.5467,106.4752,475.81941,NaN,NaN
2019-12-29,306244.474,130859.387,201994.7663,138376.8107,87750.6643,46629.5082,100930.7727,78981.8883,55867.364,74234.5589,...,NaN,1056.3412,174.8999,588.4604,1222.2517,347.5467,106.4752,475.81941,NaN,NaN
2019-12-30,307394.5953,130177.9395,200804.8232,137537.7776,87025.7107,46319.3556,100784.7093,78516.8751,55622.6235,74004.7385,...,NaN,1059.5436,175.2751,589.7174,1261.599,347.7341,106.535,476.85288,NaN,NaN
2019-12-31,311967.5198,130586.4874,201311.6576,138114.0757,87066.5431,46467.4198,100784.7093,78749.8954,55841.2198,74045.3951,...,NaN,1062.3466,176.228,592.9269,1196.5428,347.7926,105.9081,481.26236,NaN,NaN
2020-01-01,314620.1052,130586.4874,201311.6576,138114.0757,87066.5431,46467.4198,100784.7093,78749.8954,55841.2198,74045.3951,...,NaN,1062.3466,176.228,592.9269,1196.5428,347.7926,105.9081,481.26236,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-27,636589.7364,616964.4262,599568.2855,471773.186,326308.8341,157842.2617,151727.0889,139523.7607,135375.1431,123059.5626,...,2012.6253,1602.5216,941.5177,889.108,1063.2859,848.0377,824.5353,1055.96383,796.90717,773.41906
2025-01-28,630335.3754,623523.5822,602662.3704,475922.5728,329064.7101,161485.7598,150421.5398,139524.3424,134450.8345,123014.0709,...,2020.7931,1598.0797,944.775,892.1841,1079.972,856.3546,827.8285,1059.81458,796.88781,771.55758
2025-01-29,633635.5416,621063.9221,598817.3137,474006.9472,326813.7164,160630.1932,151979.4987,139497.935,134242.4535,123009.3597,...,2028.2496,1607.1581,955.8169,893.6065,1032.244,869.4536,833.0379,1070.21605,805.85034,773.41257
2025-01-30,627680.5658,623698.4807,603869.4574,477026.5187,328732.0224,160831.145,153078.0222,141037.1714,135737.2246,124433.6848,...,2033.1613,1607.3259,966.5464,903.6377,1049.4199,862.7172,835.7921,1082.01115,819.09017,781.66441
2025-01-31,624339.2202,621484.3845,600980.5568,474790.0807,326677.4764,160252.6018,153000.6655,139694.6932,135166.3995,123363.6175,...,2033.1613,1607.3259,975.1428,911.6748,1015.674,860.7978,832.638,1094.14652,829.53619,781.66441

In [11]:
aum_d_to_w = aum_d.ffill().resample('W-FRI').ffill()

C:\Users\USER\AppData\Local\Temp\ipykernel_30280\2989770733.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  aum_d_to_w = aum_d.ffill().resample('W-FRI').ffill()

In [12]:
aum_d_to_w.iloc[-1].to_csv('aum_w_recently.csv')

## 데이터 합치기

In [14]:
universe_df = pd.read_csv('universe.csv')
universe_df = universe_df.set_index('Full_ticker')
ff_w_df = pd.read_csv('ff_w_recently.csv', index_col=0)
aum_w_df = pd.read_csv('aum_w_recently.csv', index_col=0)

In [15]:
df = pd.concat([universe_df, ff_w_df, aum_w_df], axis= 1, join ="inner",ignore_index = True)

In [16]:
df

,0,1,2,3,4,5,6,7,8,9
SPY US Equity,SPDR S&P 500 ETF Trust,SPY US,주식,Blend,Large,NaN,DM,US,-3338.9339,624339.22020
VOO US Equity,Vanguard S&P 500 ETF,VOO US,주식,Blend,Large,NaN,DM,US,1507.5264,621484.38450
IVV US Equity,iShares Core S&P 500 ETF,IVV US,주식,Blend,Large,NaN,DM,US,-1693.6950,600980.55680
VTI US Equity,Vanguard Total Stock Market ETF,VTI US,주식,Blend,NaN,NaN,DM,US,510.8661,474790.08070
QQQ US Equity,Invesco QQQ Trust Series 1,QQQ US,주식,Growth,Large,NaN,DM,US,-718.4490,326677.47640
...,...,...,...,...,...,...,...,...,...,...
DBA US Equity,Invesco DB Agriculture Fund,DBA US,원자재,agriculture,NaN,NaN,NaN,NaN,2.7586,860.79780
ROLL LN Equity,iShares Bloomberg Enhanced Roll Yield Commodit...,ROLL LN,원자재,diversified,NaN,NaN,NaN,NaN,20.7200,832.63800
CGL CN Equity,iShares Gold Bullion ETF,CGL CN,원자재,Precious_metals,NaN,NaN,NaN,NaN,3.7706,1094.14652
ZGOLD TI Equity,Ziraat Portfoy Gold Participation ETF,ZGOLD TI,원자재,Precious_metals,NaN,NaN,NaN,NaN,0.0000,829.53619
XGDE GR Equity,Xtrackers IE Physical Gold EUR Hedged ETC Secu...,XGDE GR,원자재,Precious_metals,NaN,NaN,NaN,NaN,1.1816,781.66441

In [17]:
df = df[[0,9,8,2,3,4,5,6,7]]
df.columns = ['name','aum','ff','asset','Strategy1', 'Strategy2','Strategy3','DM/EM','Country']

In [18]:
df['aum'] = df['aum'].fillna(0)
df['ff'] = df['ff'].fillna(0)

C:\Users\USER\AppData\Local\Temp\ipykernel_30280\3584040796.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['aum'] = df['aum'].fillna(0)
C:\Users\USER\AppData\Local\Temp\ipykernel_30280\3584040796.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ff'] = df['ff'].fillna(0)

In [19]:
df.to_csv('data.csv')

# 자산군 분류별 전처리

In [21]:
# Fund Flow를 자산유형(asset)과 스타일1(c1) 기준으로 합산
fund_flow_summary1 = df.groupby(['asset', 'Strategy1'])[['ff','aum']].sum().reset_index()
fund_flow_summary2 = df.groupby(['asset', 'Strategy2'])[['ff','aum']].sum().reset_index()
fund_flow_summary3 = df.groupby(['asset', 'Strategy3'])[['ff','aum']].sum().reset_index()
fund_flow_summary4 = df.groupby(['asset', 'DM/EM'])[['ff','aum']].sum().reset_index()
fund_flow_summary5 = df.groupby(['asset', 'Country'])[['ff','aum']].sum().reset_index()

In [22]:
fund_flow_summary1.columns = ['자산군','분류','Fund_Flow','AUM']
fund_flow_summary2.columns = ['자산군','분류','Fund_Flow','AUM']
fund_flow_summary3.columns = ['자산군','분류','Fund_Flow','AUM']
fund_flow_summary4.columns = ['자산군','분류','Fund_Flow','AUM']
fund_flow_summary5.columns = ['자산군','분류','Fund_Flow','AUM']

In [23]:
fund_flow_df = pd.concat([fund_flow_summary1,fund_flow_summary2,fund_flow_summary3,fund_flow_summary4,fund_flow_summary5],axis=0)
fund_flow_df = fund_flow_df.round(1)
fund_flow_df

    자산군                분류  Fund_Flow        AUM
0    대체      equity_hedge       33.8     1876.5
1    대체             macro      577.1   162300.2
2    대체    multi_strategy        4.8      699.8
3   원자재      Energy&Fuels      141.0     1015.7
4   원자재   Precious_metals      968.1   275011.8
5   원자재       agriculture        2.8      860.8
6   원자재       diversified      -36.0    20298.8
7   원자재  industrial_metal        7.8     1218.2
8    주식             Blend     4494.8  7974813.4
9    주식            Growth     3075.3  1551033.4
10   주식             Value      734.8  1125434.4
11   채권               agg     1939.2   744553.7
12   채권        asset_back     1418.0    25621.7
13   채권         bank_loan     1104.7    27128.2
14   채권       convertible       34.7    13348.3
15   채권         corporate     2083.1   575606.8
16   채권        government     -538.5   670026.6
17   채권         inflation      465.7    68669.8
18   채권      mortage_back      803.3    78705.6
19   채권          prefered       14.6    38675.2
0    주식             Large     2906.4  7395675.7
1    주식               mid      598.8   432739.6
2    주식             small      262.5   513479.5
3    채권                A+     1672.7   612525.7
4    채권                HY     1011.9   124096.7
5    채권                IG     2872.3  1154050.8
0    주식     Communication      109.9    38899.0
1    주식     discretionary      436.8    38800.8
2    주식            energy     -457.1    68627.8
3    주식         financial     1947.7   115874.8
4    주식        healthcare      225.0    97968.3
5    주식        industrial     1100.1    54941.9
6    주식         materials     -269.8    37388.5
7    주식           staples     -168.3    25282.7
8    주식        technology     1847.5   387889.9
9    주식         utilities     -353.9    31296.5
10   채권      intermediate      816.1   355483.9
11   채권              long      235.3   241955.3
12   채권             short     1107.3   322523.3
0    주식                DM     8331.2  8797502.3
1    주식                EM    -1062.6   830413.9
0    주식             China     -791.4   321113.3
1    주식            Europe      210.7   132038.9
2    주식             Japan      966.6   596752.2
3    주식             Korea        0.0    10361.4
4    주식            Taiwan        0.0    77000.1
5    주식                US     5277.8  4782003.9
6    주식             india     -221.1    83239.8

In [24]:
asset_order = ['주식','채권','원자재','대체']
calssification_order =['DM',
                       'EM',
                       'US',
                       'Europe',
                       'Japan',
                       'China',
                       'Taiwan',
                       'Korea',
                       'india',
                       'Growth',
                       'Value',
                       'Large',
                       'mid',
                       'small',                
                       'Communication',
                       'discretionary',
                       'staples',
                       'energy',
                       'financial',
                       'healthcare',
                       'industrial',
                       'materials',
                       'technology',
                       'utilities',
                       'agg',
                       'bank_loan',
                       'convertible',
                       'corporate',
                       'government',
                       'inflation',
                       'mortage_back',
                       'A+',
                       'IG',
                       'HY',
                       'long',
                       'intermediate',
                       'short',
                       'diversified',
                       'Precious_metals',
                       'Energy&Fuels',
                       'industrial_metal',
                       'agriculture',
                       'multi_strategy',
                       'macro',
                       'equity_hedge']

fund_flow_df['자산군'] = pd.Categorical(fund_flow_df['자산군'], categories=asset_order, ordered=True)
fund_flow_df['분류'] = pd.Categorical(fund_flow_df['분류'], categories=calssification_order, ordered=True)

# # 정렬 수행
fund_flow_df_sorted = fund_flow_df.sort_values(by=['자산군','분류'])

In [25]:
fund_flow_df_sorted

    자산군                분류  Fund_Flow        AUM
0    주식                DM     8331.2  8797502.3
1    주식                EM    -1062.6   830413.9
5    주식                US     5277.8  4782003.9
1    주식            Europe      210.7   132038.9
2    주식             Japan      966.6   596752.2
0    주식             China     -791.4   321113.3
4    주식            Taiwan        0.0    77000.1
3    주식             Korea        0.0    10361.4
6    주식             india     -221.1    83239.8
9    주식            Growth     3075.3  1551033.4
10   주식             Value      734.8  1125434.4
0    주식             Large     2906.4  7395675.7
1    주식               mid      598.8   432739.6
2    주식             small      262.5   513479.5
0    주식     Communication      109.9    38899.0
1    주식     discretionary      436.8    38800.8
7    주식           staples     -168.3    25282.7
2    주식            energy     -457.1    68627.8
3    주식         financial     1947.7   115874.8
4    주식        healthcare      225.0    97968.3
5    주식        industrial     1100.1    54941.9
6    주식         materials     -269.8    37388.5
8    주식        technology     1847.5   387889.9
9    주식         utilities     -353.9    31296.5
8    주식               NaN     4494.8  7974813.4
11   채권               agg     1939.2   744553.7
13   채권         bank_loan     1104.7    27128.2
14   채권       convertible       34.7    13348.3
15   채권         corporate     2083.1   575606.8
16   채권        government     -538.5   670026.6
17   채권         inflation      465.7    68669.8
18   채권      mortage_back      803.3    78705.6
3    채권                A+     1672.7   612525.7
5    채권                IG     2872.3  1154050.8
4    채권                HY     1011.9   124096.7
11   채권              long      235.3   241955.3
10   채권      intermediate      816.1   355483.9
12   채권             short     1107.3   322523.3
12   채권               NaN     1418.0    25621.7
19   채권               NaN       14.6    38675.2
6   원자재       diversified      -36.0    20298.8
4   원자재   Precious_metals      968.1   275011.8
3   원자재      Energy&Fuels      141.0     1015.7
7   원자재  industrial_metal        7.8     1218.2
5   원자재       agriculture        2.8      860.8
2    대체    multi_strategy        4.8      699.8
1    대체             macro      577.1   162300.2
0    대체      equity_hedge       33.8     1876.5

In [26]:
fund_flow_df_sorted['ff/aum']= round(fund_flow_df_sorted['Fund_Flow']/fund_flow_df_sorted['AUM']*100,2)
fund_flow_df_sorted = fund_flow_df_sorted.dropna(subset=["분류"])

### 분류 네임 맞추기

In [28]:
name_new_list = df_raw['BM'].iloc[5:53,11].dropna().to_list()

In [29]:
fund_flow_df_sorted['분류'] = name_new_list

C:\Users\USER\AppData\Local\Temp\ipykernel_30280\3560579345.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fund_flow_df_sorted['분류'] = name_new_list

In [30]:
fund_flow_df_sorted

    자산군                   분류  Fund_Flow        AUM  ff/aum
0    주식                   DM     8331.2  8797502.3    0.09
1    주식                   EM    -1062.6   830413.9   -0.13
5    주식                   US     5277.8  4782003.9    0.11
1    주식               Europe      210.7   132038.9    0.16
2    주식                Japan      966.6   596752.2    0.16
0    주식                China     -791.4   321113.3   -0.25
4    주식               Taiwan        0.0    77000.1    0.00
3    주식                Korea        0.0    10361.4    0.00
6    주식                India     -221.1    83239.8   -0.27
9    주식               Growth     3075.3  1551033.4    0.20
10   주식                Value      734.8  1125434.4    0.07
0    주식                Large     2906.4  7395675.7    0.04
1    주식                  Mid      598.8   432739.6    0.14
2    주식                Small      262.5   513479.5    0.05
0    주식        Communication      109.9    38899.0    0.28
1    주식        Discretionary      436.8    38800.8    1.13
7    주식              Staples     -168.3    25282.7   -0.67
2    주식               Energy     -457.1    68627.8   -0.67
3    주식            Financial     1947.7   115874.8    1.68
4    주식           Healthcare      225.0    97968.3    0.23
5    주식           Industrial     1100.1    54941.9    2.00
6    주식            Materials     -269.8    37388.5   -0.72
8    주식           Technology     1847.5   387889.9    0.48
9    주식             Utilites     -353.9    31296.5   -1.13
11   채권                  Agg     1939.2   744553.7    0.26
13   채권            Bank_loan     1104.7    27128.2    4.07
14   채권          Convertible       34.7    13348.3    0.26
15   채권            Corporate     2083.1   575606.8    0.36
16   채권           Government     -538.5   670026.6   -0.08
17   채권  Inflation_protected      465.7    68669.8    0.68
18   채권      Mortgage_Backed      803.3    78705.6    1.02
3    채권              A_above     1672.7   612525.7    0.27
5    채권                   IG     2872.3  1154050.8    0.25
4    채권                   HY     1011.9   124096.7    0.82
11   채권                 Long      235.3   241955.3    0.10
10   채권         Intermediate      816.1   355483.9    0.23
12   채권                  Low     1107.3   322523.3    0.34
6   원자재          Diversified      -36.0    20298.8   -0.18
4   원자재      Precious_metals      968.1   275011.8    0.35
3   원자재          Energy&Fuel      141.0     1015.7   13.88
7   원자재    Industrial_metals        7.8     1218.2    0.64
5   원자재          Agriculture        2.8      860.8    0.33
2    대체       multi_strategy        4.8      699.8    0.69
1    대체                macro      577.1   162300.2    0.36
0    대체         equity_hedge       33.8     1876.5    1.80

In [31]:
fund_flow_df_sorted.to_csv('asset_ff,aum.csv',encoding='utf-8-sig', index=False)

## 자산군별 수익률 데이터

In [33]:
df_price = pd.DataFrame(df_raw['asset_price'].iloc[16:,])
df_price = df_price.rename(columns=df_raw['asset_price'].iloc[12,1:49])

In [34]:
df_price.set_index('Unnamed: 0', inplace=True)

In [35]:
return_1w = round(df_price.pct_change(periods=7)*100,1)
return_1m = round(df_price.pct_change(periods=30)*100,1)

C:\Users\USER\AppData\Local\Temp\ipykernel_30280\2361069769.py:1: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_1w = round(df_price.pct_change(periods=7)*100,1)
C:\Users\USER\AppData\Local\Temp\ipykernel_30280\2361069769.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  return_1w = round(df_price.pct_change(periods=7)*100,1)
C:\Users\USER\AppData\Local\Temp\ipykernel_30280\2361069769.py:2: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_1m = round(df_price.pct_change(periods=30)*100,1)
C:\Users\USER\AppData\Local\Temp\ipykernel_30280\2361069769.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  return_1m = round(df_price.pct_change(periods=30)*100,1)

In [36]:
fund_flow_df_sorted['return_1w'] = fund_flow_df_sorted['분류'].map(return_1w.iloc[-1])
fund_flow_df_sorted['return_1m'] = fund_flow_df_sorted['분류'].map(return_1m.iloc[-1])

C:\Users\USER\AppData\Local\Temp\ipykernel_30280\4041951676.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fund_flow_df_sorted['return_1w'] = fund_flow_df_sorted['분류'].map(return_1w.iloc[-1])
C:\Users\USER\AppData\Local\Temp\ipykernel_30280\4041951676.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fund_flow_df_sorted['return_1m'] = fund_flow_df_sorted['분류'].map(return_1m.iloc[-1])

In [37]:
new_order = ['자산군','분류','AUM','Fund_Flow','ff/aum','return_1w','return_1m']
fund_flow_df_sorted = fund_flow_df_sorted[new_order]

In [38]:
fund_flow_df_sorted.to_csv('asset_ff,aum.csv',encoding='utf-8-sig', index=False)

In [39]:
pd.read_csv("asset_ff,aum.csv")

,자산군,분류,AUM,Fund_Flow,ff/aum,return_1w,return_1m
0,주식,DM,8797502.3,8331.2,0.09,-0.5,3.5
1,주식,EM,830413.9,-1062.6,-0.13,0.3,1.6
2,주식,US,4782003.9,5277.8,0.11,-1.0,2.7
3,주식,Europe,132038.9,210.7,0.16,1.8,6.3
4,주식,Japan,596752.2,966.6,0.16,-0.9,-0.8
5,주식,China,321113.3,-791.4,-0.25,-0.4,-3.0
6,주식,Taiwan,77000.1,0.0,0.00,0.0,3.0
7,주식,Korea,10361.4,0.0,0.00,-0.8,4.9
8,주식,India,83239.8,-221.1,-0.27,1.7,-1.3
9,주식,Growth,1551033.4,3075.3,0.20,-1.2,2.6
10,주식,Value,1125434.4,734.8,0.07,0.4,4.1
11,주식,Large,7395675.7,2906.4,0.04,-0.5,3.2
12,주식,Mid,432739.6,598.8,0.14,-0.3,3.8
13,주식,Small,513479.5,262.5,0.05,-0.3,2.5
14,주식,Communication,38899.0,109.9,0.28,-4.2,2.6
15,주식,Discretionary,38800.8,436.8,1.13,1.0,4.2
16,주식,Staples,25282.7,-168.3,-0.67,1.6,1.6
17,주식,Energy,68627.8,-457.1,-0.67,-2.5,2.4
18,주식,Financial,115874.8,1947.7,1.68,1.0,5.8
19,주식,Healthcare,97968.3,225.0,0.23,1.5,6.1
20,주식,Industrial,54941.9,1100.1,2.00,-1.5,4.4
21,주식,Materials,37388.5,-269.8,-0.72,-0.4,4.9
22,주식,Technology,387889.9,1847.5,0.48,-3.5,-1.1
23,주식,Utilites,31296.5,-353.9,-1.13,-0.8,1.8
24,채권,Agg,744553.7,1939.2,0.26,0.4,0.5
25,채권,Bank_loan,27128.2,1104.7,4.07,-0.0,0.7
26,채권,Convertible,13348.3,34.7,0.26,-0.4,3.0
27,채권,Corporate,575606.8,2083.1,0.36,0.3,0.6
28,채권,Government,670026.6,-538.5,-0.08,0.1,0.6
29,채권,Inflation_protected,68669.8,465.7,0.68,0.6,1.2
30,채권,Mortgage_Backed,78705.6,803.3,1.02,0.5,0.5
31,채권,A_above,612525.7,1672.7,0.27,0.6,0.5
32,채권,IG,1154050.8,2872.3,0.25,0.3,0.5
33,채권,HY,124096.7,1011.9,0.82,0.2,1.4
34,채권,Long,241955.3,235.3,0.10,0.6,0.5
35,채권,Intermediate,355483.9,816.1,0.23,0.6,0.6
36,채권,Low,322523.3,1107.3,0.34,0.2,0.4
37,원자재,Diversified,20298.8,-36.0,-0.18,-1.0,4.0
38,원자재,Precious_metals,275011.8,968.1,0.35,1.2,7.6
39,원자재,Energy&Fuel,1015.7,141.0,13.88,-2.9,1.1
40,원자재,Industrial_metals,1218.2,7.8,0.64,-2.2,1.5
41,원자재,Agriculture,860.8,2.8,0.33,0.7,3.9
42,대체,multi_strategy,699.8,4.8,0.69,-0.0,1.8
43,대체,macro,162300.2,577.1,0.36,-3.2,7.8
44,대체,equity_hedge,1876.5,33.8,1.80,NaN,NaN