In [2]:
import pandas as pd

# 엑셀 파일 불러오기 (sheet_name으로 특정 시트 지정 가능)
df_raw = pd.read_excel("etf_raw_daily.xlsx", sheet_name='FF_d')

In [3]:
ff_d = pd.DataFrame(df_raw.iloc[13:,])
ff_d = ff_d.rename( columns = df_raw.iloc[10,1:])
ff_d = ff_d.set_index('Unnamed: 0')
ff_d

,SPY US Equity,VOO US Equity,IVV US Equity,VTI US Equity,QQQ US Equity,VUG US Equity,1306 JP Equity,VEA US Equity,VTV US Equity,IEFA US Equity,...,ENCO LN Equity,CCUSAS SW Equity,AAAU US Equity,BAR US Equity,USO US Equity,DBA US Equity,ROLL LN Equity,CGL CN Equity,ZGOLD TI Equity,XGDE GR Equity
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
2019-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-12-30,224.7472,55.2044,-48.3705,-96.9306,-190.9156,15.8744,-0.0147,0.534,20.4527,0,...,NaN,0,0,0,40.0303,0,0,0,NaN,NaN
2019-12-31,4572.9244,20.2073,-97.032,163.3729,148.8862,15.5704,NaN,0.2451,37.0816,0,...,NaN,0,0,0,-52.4127,0,0,0,NaN,NaN
2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-27,6141.6511,-56.5979,-240.8267,66.3541,4342.9273,-9.5818,-0.1605,0.472,-8.6908,0,...,0,0,0,0,179.5089,0,18.4209,0,0,0
2025-01-28,-3295.6286,870.5774,-2430.4577,-27.5649,-2427.8609,48.8735,37.3446,0.5818,51.7528,0,...,-0.419,0,0,0,7.8694,0,0.7641,0,0,0
2025-01-29,-30.0939,455.8879,-1028.1164,148.9077,-1458.4165,158.1184,0,1.5758,58.6136,0,...,0,0,9.5358,0,-30.9899,0,1.535,3.7706,0,1.1816
2025-01-30,-2813.5169,-653.4532,1884.7172,144.2026,444.7298,32.476,0,0.1419,98.1612,0,...,-1.8148,0,0,0,15.5198,0,0,0,0,0
2025-01-31,-3341.3456,891.1122,120.9886,178.9666,-1619.8287,41.8794,0.0683,0.733,208.1766,0,...,NaN,NaN,0,0,-30.9572,2.7586,0,0,0,NaN

In [4]:
ff_d_to_w = ff_d.resample('W-FRI').sum()

In [5]:
universe_df = pd.read_csv('universe.csv')
universe_df = universe_df.set_index('Full_ticker')

In [6]:
etf_ff = pd.concat([universe_df,ff_d_to_w.T.iloc[:,-56:]], axis=1,join ="inner")
etf_ff

,NAME,Ticker,Asset,Strategy1,Strategy2,Strategy3,DM/EM,Country,2024-05-31 00:00:00,2024-06-07 00:00:00,...,2024-11-29 00:00:00,2024-12-06 00:00:00,2024-12-13 00:00:00,2024-12-20 00:00:00,2024-12-27 00:00:00,2025-01-03 00:00:00,2025-01-10 00:00:00,2025-01-17 00:00:00,2025-01-24 00:00:00,2025-01-31 00:00:00
SPY US Equity,SPDR S&P 500 ETF Trust,SPY US,주식,Blend,Large,NaN,DM,US,7532.3413,-4019.9407,...,964.0193,3929.8612,15134.5138,-7005.6693,-6886.1554,4892.1516,-3405.1734,3304.9024,-13614.2772,-3338.9339
VOO US Equity,Vanguard S&P 500 ETF,VOO US,주식,Blend,Large,NaN,DM,US,1633.0732,11853.7822,...,1358.62,-4396.1045,1873.7186,4207.2357,6043.9611,5242.9439,6615.4745,5242.1602,6251.2023,1507.5264
IVV US Equity,iShares Core S&P 500 ETF,IVV US,주식,Blend,Large,NaN,DM,US,237.3787,-14867.7343,...,4250.3174,-416.6569,-9619.997,35889.1081,-5567.4839,2102.6933,321.7613,2339.7929,-1641.832,-1693.695
VTI US Equity,Vanguard Total Stock Market ETF,VTI US,주식,Blend,NaN,NaN,DM,US,77.2357,1520.7371,...,761.2384,3235.1818,1630.575,-1056.0663,384.2798,217.0739,1242.362,1234.466,853.2683,510.8661
QQQ US Equity,Invesco QQQ Trust Series 1,QQQ US,주식,Growth,Large,NaN,DM,US,-1200.343,185.4594,...,2842.4523,-1627.9412,-1269.4754,1924.9817,-1542.1743,2840.1391,-1148.4438,1141.9194,1991.9018,-718.449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DBA US Equity,Invesco DB Agriculture Fund,DBA US,원자재,agriculture,NaN,NaN,NaN,NaN,0,-6.3808,...,0,-10.6335,5.4944,4.125,7.8237,3.9485,17.0231,10.6576,8.1921,2.7586
ROLL LN Equity,iShares Bloomberg Enhanced Roll Yield Commodit...,ROLL LN,원자재,diversified,NaN,NaN,NaN,NaN,0,21.7295,...,-17.635,3.2934,15.3148,-557.5148,-5.4512,-1.3318,0,-2.2984,-2.9332,20.72
CGL CN Equity,iShares Gold Bullion ETF,CGL CN,원자재,Precious_metals,NaN,NaN,NaN,NaN,0,0,...,0,-7.4377,-7.4847,0,0,0,3.6206,0,0,3.7706
ZGOLD TI Equity,Ziraat Portfoy Gold Participation ETF,ZGOLD TI,원자재,Precious_metals,NaN,NaN,NaN,NaN,0,-17.9667,...,0,0,0,0,-69.7824,-288.3062,-74.235,-14.4497,0,0
XGDE GR Equity,Xtrackers IE Physical Gold EUR Hedged ETC Secu...,XGDE GR,원자재,Precious_metals,NaN,NaN,NaN,NaN,-1.1136,-3.6591,...,1.152,1.1669,-5.0184,33.681,-8.3151,-1.1356,0,31.4298,-1.4521,1.1816

In [7]:
stock_ff_12w = etf_ff[etf_ff['Asset']=="주식"].iloc[:,8:].sum()
bond_ff_12w = etf_ff[etf_ff['Asset']=="채권"].iloc[:,8:].sum()
commodity_ff_12w = etf_ff[etf_ff['Asset']=="원자재"].iloc[:,8:].sum()

In [8]:
asset_ff_12w = pd.concat([stock_ff_12w,bond_ff_12w,commodity_ff_12w],axis=1)

In [9]:
asset_ff_12w.columns = ['Stock','Bond','Commodity']

In [10]:
asset_ff_12w = asset_ff_12w.astype(int)
asset_ff_12w

                     Stock   Bond  Commodity
2024-05-31 00:00:00  13580   6331        681
2024-06-07 00:00:00   9501   8888        593
2024-06-14 00:00:00  10556   5310       -546
2024-06-21 00:00:00  40812   6792        265
2024-06-28 00:00:00  20208   5664        473
2024-07-05 00:00:00   3791   7963        710
2024-07-12 00:00:00  38473  12161        414
2024-07-19 00:00:00  44409   9759       1030
2024-07-26 00:00:00  13933  10143       1336
2024-08-02 00:00:00  19890   6358       -212
2024-08-09 00:00:00   7206   3800      -1189
2024-08-16 00:00:00  17584   9684        196
2024-08-23 00:00:00  21060   9842        392
2024-08-30 00:00:00  12441   8042        690
2024-09-06 00:00:00   7573  10134         53
2024-09-13 00:00:00   2254  10183       1009
2024-09-20 00:00:00  25972   4822       -295
2024-09-27 00:00:00  39593   6030        826
2024-10-04 00:00:00  24214   7295        499
2024-10-11 00:00:00  32509   6305       -360
2024-10-18 00:00:00  22118   8585       2456
2024-10-25 00:00:00  10804   2500       1383
2024-11-01 00:00:00  14247  10764        191
2024-11-08 00:00:00  56113   8956       -604
2024-11-15 00:00:00  34704    -17      -1764
2024-11-22 00:00:00  14101   9326        605
2024-11-29 00:00:00  24811   3659       -292
2024-12-06 00:00:00  16106   7403       -904
2024-12-13 00:00:00  31127   9114       -706
2024-12-20 00:00:00  64990   -723        736
2024-12-27 00:00:00  -8030   5090       -249
2025-01-03 00:00:00  31209   6531       -356
2025-01-10 00:00:00  13686   9217        507
2025-01-17 00:00:00  27398   7371       1764
2025-01-24 00:00:00   5965   6440      -1503
2025-01-31 00:00:00   8456   7255       1083

In [11]:
asset_ff_12w.to_csv('asset_ff_12w.csv')

# AUM_timeseries

In [13]:
df_AUM = pd.read_excel("etf_raw_daily.xlsx", sheet_name='AUM_d')

In [14]:
aum_d = pd.DataFrame(df_AUM.iloc[13:,])
aum_d = aum_d.rename(columns = df_AUM.iloc[10,1:])
aum_d = aum_d.set_index('Unnamed: 0')

friday_df_aum = aum_d[aum_d.index.weekday == 4]
friday_df_aum = friday_df_aum.astype(float).round(1)

In [15]:
etf_aum=pd.concat([universe_df,friday_df_aum.T.iloc[:,-56:]], axis=1,join ="inner")

In [16]:
stock_aum_12w = etf_aum[etf_aum['Asset']=="주식"].iloc[:,8:].sum()
bond_aum_12w = etf_aum[etf_aum['Asset']=="채권"].iloc[:,8:].sum()
commodity_aum_12w = etf_aum[etf_aum['Asset']=="원자재"].iloc[:,8:].sum()

In [17]:
asset_aum_12w = pd.concat([stock_aum_12w,bond_aum_12w,commodity_aum_12w],axis=1)
asset_aum_12w.columns = ['Stock','Bond','Commodity']

In [18]:
asset_aum_12w

                          Stock       Bond  Commodity
2024-05-31 00:00:00   8947351.3  1975590.3   249543.6
2024-06-07 00:00:00   9012038.1  1984905.7   245801.4
2024-06-14 00:00:00   9060875.5  2007368.5   246519.5
2024-06-21 00:00:00   9121820.7  2011768.6   247854.7
2024-06-28 00:00:00   9148287.5  2009527.8   248969.4
2024-07-05 00:00:00   9299329.9  2028831.0   255331.5
2024-07-12 00:00:00   9482105.3  2057963.2   257862.0
2024-07-19 00:00:00   9365852.3  2064665.9   256606.7
2024-07-26 00:00:00   9309220.5  2077182.9   255028.0
2024-08-02 00:00:00   9067217.0  2116143.8   262547.8
2024-08-09 00:00:00   9106781.5  2108461.5   257237.6
2024-08-16 00:00:00   9484467.8  2131118.1   263220.7
2024-08-23 00:00:00   9653497.7  2158546.0   267418.6
2024-08-30 00:00:00   9685290.4  2157492.3   267952.1
2024-09-06 00:00:00   9331078.9  2184686.9   266143.6
2024-09-13 00:00:00   9623707.8  2204986.1   274677.6
2024-09-20 00:00:00   9795722.0  2209789.8   278781.0
2024-09-27 00:00:00   9943791.9  2217120.1   284874.9
2024-10-04 00:00:00  10025692.6  2199211.6   285464.4
2024-10-11 00:00:00  10138952.4  2197835.3   284601.1
2024-10-18 00:00:00  10205307.2  2207445.4   292047.6
2024-10-25 00:00:00  10078491.5  2193393.4   295324.5
2024-11-01 00:00:00   9986961.0  2189224.8   295261.1
2024-11-08 00:00:00  10432701.5  2211411.7   288779.7
2024-11-15 00:00:00  10237413.4  2191773.3   275581.8
2024-11-22 00:00:00  10428730.9  2201631.6   288078.2
2024-11-29 00:00:00  10559104.0  2233724.3   283537.5
2024-12-06 00:00:00  10654825.3  2241354.1   281562.7
2024-12-13 00:00:00  10597897.4  2224892.0   282767.3
2024-12-20 00:00:00  10377580.2  2203189.3   277716.6
2024-12-27 00:00:00  10422218.5  2198028.6   277631.7
2025-01-03 00:00:00  10432229.5  2203736.0   280178.3
2025-01-10 00:00:00  10259997.9  2195877.4   285609.3
2025-01-17 00:00:00  10558900.5  2222026.5   290271.9
2025-01-24 00:00:00  10743843.6  2238746.4   294398.0
2025-01-31 00:00:00  10706569.4  2251020.6   298405.3

# FF + AUM

In [20]:
asset_ff_aum = asset_ff_12w / asset_aum_12w *100

In [21]:
asset_ff_aum = asset_ff_aum.round(2)

In [22]:
asset_ff_aum.to_csv('asset_ff_aum.csv')

# 4주 누적

In [57]:
asset_ff_12w.rolling(window=4).sum()/asset_aum_12w*100

                        Stock      Bond  Commodity
2024-05-31 00:00:00       NaN       NaN        NaN
2024-06-07 00:00:00       NaN       NaN        NaN
2024-06-14 00:00:00       NaN       NaN        NaN
2024-06-21 00:00:00  0.816164  1.358059   0.400638
2024-06-28 00:00:00  0.886253  1.326381   0.315300
2024-07-05 00:00:00  0.810456  1.268169   0.353266
2024-07-12 00:00:00  1.089252  1.583119   0.722092
2024-07-19 00:00:00  1.141178  1.721683   1.023746
2024-07-26 00:00:00  1.080713  1.926937   1.368477
2024-08-02 00:00:00  1.287109  1.815614   0.978108
2024-08-09 00:00:00  0.938180  1.425684   0.375140
2024-08-16 00:00:00  0.617989  1.407008   0.049768
2024-08-23 00:00:00  0.680997  1.375185  -0.304018
2024-08-30 00:00:00  0.601851  1.453910   0.033215
2024-09-06 00:00:00  0.628630  1.725739   0.500106
2024-09-13 00:00:00  0.450221  1.732483   0.780551
2024-09-20 00:00:00  0.492460  1.501546   0.522632
2024-09-27 00:00:00  0.758182  1.405833   0.559193
2024-10-04 00:00:00  0.917971  1.288189   0.714275
2024-10-11 00:00:00  1.206121  1.112549   0.235417
2024-10-18 00:00:00  1.160514  1.278174   1.171384
2024-10-25 00:00:00  0.889468  1.125425   1.346993
2024-11-01 00:00:00  0.797820  1.286026   1.242968
2024-11-08 00:00:00  0.989983  1.393002   1.186371
2024-11-15 00:00:00  1.131809  1.013015  -0.288118
2024-11-22 00:00:00  1.142661  1.318522  -0.545685
2024-11-29 00:00:00  1.228599  0.981500  -0.724772
2024-12-06 00:00:00  0.842079  0.908870  -0.836403
2024-12-13 00:00:00  0.812850  1.325997  -0.458681
2024-12-20 00:00:00  1.320481  0.882947  -0.419852
2024-12-27 00:00:00  0.999720  0.950124  -0.404493
2025-01-03 00:00:00  1.143533  0.908094  -0.205226
2025-01-10 00:00:00  0.992739  0.916035   0.223382
2025-01-17 00:00:00  0.608615  1.269517   0.573945
2025-01-24 00:00:00  0.728399  1.320337   0.139947
2025-01-31 00:00:00  0.518420  1.345301   0.620297